#########################
## PV para WORDPRESS  ###
########################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wordpress
  hostPath:
    path: /Users/martinmorona/github_martinmorana/k8s/K8s_al_completo/Ejemplo/datos/wordpress
    
