version: '2'

services:
  jenkins:
    container_name: jenkinsAnsible
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - '8080:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local
